config/routes.rb
Rails.application.routes.draw do
 resources :posts

  root 'posts#index'

 
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  end

  def new
  	@post = Post.new
  	respond_to do |format|
  		format.html
  		format.js { flash[:notice] = "Houston we have a problem"}
  	end
  end

  def show
  	@post = Post.find(params[:id])
  end

  
  def create
  	@post = Post.new(params.require(:post).permit(:title, :body))
  	if @post.save
  		respond_to do |format|
  			format.html { redirect_to @post, notice: "New Post created" }
  			format.js { flash[:notice] = "Houston we have a problem"}
  		end
	else
		respond_to do |format|
	  		format.html {render :new}
	  		format.js
	  	end
	  end
end

  def destroy
  	@post = Post.find(params[:id])
  	@post.destroy
  	respond_to do |format|
  	  format.html {redirect_to posts_path, notice: "Post purged!"}
  	  format.js {render nothing: true}
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/Shared/_flash.html.erb
<% if flash[:notice] %>
<div id="notice">
<%= flash[:notice] %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UjsPlayground</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<nav>
	<%= link_to 'all posts', posts_path %>
	<%= link_to 'new post', new_post_path %>
	</nav>
</header>
<%= render 'shared/flash' %>


<%= yield %>

</body>
</html>

app/views/posts/_new.html.erb
<%= form_for Post.new, remote: true do |f| %>
<% if @post.errors.any? %>
<div id="errors">
<% @post.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
</div>
<% end %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>
<p>
<%= f.label :body %><br>
<%= f.text_area :body %>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
<h3><%= link_to post.title, post %></h3>
<p><%= post.body %></p>
<p><%= link_to "Delete", post_path(post), method: :delete, remote: true, data: {confirm: "Are you sure?"} %>
</p>
<hr>
</div>

app/views/posts/create.js.erb
<% if @post.errors.any? %>
alert('something went wrong');
<% else %>
$('#posts').append("<%= j render @post %>");
$('#post_title, #post_body').val('');
<% end %>
$("#notice").html("<%= j flash[:notice] %>");

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>All posts</h1>
<div id="new-post">
<%= link_to 'new post', new_post_path, remote:true %>
</div>
<div id="post">
<%= render @posts %>
<div>

app/views/posts/new.html.erb
<h1>new post <h1>
<%= render 'new' %>

app/views/posts/new.js.erb
$('#new-post').html("<%= j render 'new' %>");

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>